server:
  port: 7000

spring:
  application:
    name: auth-service #服务名称

  profiles:
    active: '@profileActive@'

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 #nacos服务地址，将授权服务注册到nacos

jwt:
  secret: 123456789abcdefg
  expire: 604800 #token有效时长，单位：秒，总共7天
  header: token