server:
  port: 9111

spring:
  application:
    name: goods-service
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848 #nacos服务地址
  profiles:
    active: '@profileActive@'

  zipkin:
    base-url: http://127.0.0.1:9411/ #指定Zipkin服务端地址
    discoveryClientEnable: false #让nacos把base-url当成一个url，不要当成服务名
  sleuth:
    sampler:
      probability: 1.0 #采样百分比，向Zipkin服务端推送数据需要发送请求，有性能损耗，此处可按实际情况配置百分比，1.0表示百分百

mybatis:
  mapper-locations: classpath*:/mapper/*.xml
  configuration:
    # 开启下划线转驼峰
    map-underscore-to-camel-case: true

seata:
  tx-service-group: my_test_tx_group #事务分组名称，要和服务端一样，即和配置中心配置项service.vgroupMapping.my_test_tx_group=default中key的第三部分保持一致
  service:
    vgroup-mapping:
      my_test_tx_group: default #key是事务分组名称(上面配置的)，value是配置中心配置项service.vgroupMapping.my_test_tx_group=default中的value，即default
                                #也和registry.conf中nacos配置中的cluster的值一样


