spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mall?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 711454466.cn
    driver-class-name: com.mysql.cj.jdbc.Driver

# 加了以下配置才能打印出执行的SQL语句。 找不到日志文件，则启动报错
logging:
  config: classpath:logback-spring.xml
  level:
    com.wjx.study.**: debug





