server:
  port: 9110

spring:
  application:
    name: order-service #服务名称
  profiles:
    active: '@profileActive@'
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848 #nacos服务地址
    sentinel:
      transport:
        port: 9999 # 指定应用和dashboard服务交流的端口，dashboard服务需要从应用获取数据
        dashboard: localhost:8080 #指定dashboard服务的地址

mybatis:
  mapper-locations: classpath*:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true  #开启下划线转驼峰

feign:
  sentinel:
    enabled: true #开启Feign对Sentinel的支持，以实现调用时的容错处理

